# Generated by Django 3.1.7 on 2021-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('isSuspened', models.BooleanField(default=False)),
                ('number', models.CharField(default='number', max_length=64)),
                ('position', models.CharField(choices=[('MN', 'Manager'), ('DV', 'Diver'), ('SV', 'Servicer'), ('DP', 'Dispatcher'), ('PN', 'Personnel')], default='DP', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('isSuspened', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('MN', 'Manager'), ('DV', 'Diver'), ('SV', 'Servicer'), ('DP', 'Dispatcher'), ('PN', 'Personnel')], default='DV', max_length=2)),
                ('number', models.CharField(default='number', max_length=64)),
                ('isPartTime', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('isSuspened', models.BooleanField(default=False)),
                ('number', models.CharField(default='number', max_length=64)),
                ('position', models.CharField(choices=[('MN', 'Manager'), ('DV', 'Diver'), ('SV', 'Servicer'), ('DP', 'Dispatcher'), ('PN', 'Personnel')], default='MN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('isSuspened', models.BooleanField(default=False)),
                ('number', models.CharField(default='number', max_length=64)),
                ('position', models.CharField(choices=[('MN', 'Manager'), ('DV', 'Diver'), ('SV', 'Servicer'), ('DP', 'Dispatcher'), ('PN', 'Personnel')], default='PN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('entranceTime', models.DateTimeField(auto_now_add=True)),
                ('isSuspened', models.BooleanField(default=False)),
                ('number', models.CharField(default='number', max_length=64)),
                ('position', models.CharField(choices=[('MN', 'Manager'), ('DV', 'Diver'), ('SV', 'Servicer'), ('DP', 'Dispatcher'), ('PN', 'Personnel')], default='SV', max_length=2)),
                ('servingNum', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
