# Generated by Django 3.1.7 on 2021-06-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('man_management', '0001_initial'),
        ('traffic_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='traffic_control.car'),
        ),
        migrations.AddField(
            model_name='driver',
            name='line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='traffic_control.line'),
        ),
        migrations.AddField(
            model_name='customer',
            name='startLine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_control.line'),
        ),
    ]
