# Generated by Django 3.1.7 on 2021-06-11 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('man_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=64)),
                ('load', models.PositiveIntegerField()),
                ('usable', models.BooleanField(default=True)),
                ('remark', models.TextField()),
                ('num', models.CharField(default='null', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrivalTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, default='')),
                ('number', models.CharField(default='xxx', max_length=64, unique=True)),
                ('reservation', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_car', to='traffic_control.car')),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_driver', to='man_management.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineName', models.CharField(max_length=64)),
                ('length', models.PositiveIntegerField(default=0)),
                ('userable', models.BooleanField(default=True)),
                ('description', models.TextField(default='description')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopName', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='traffic_control.line')),
            ],
        ),
        migrations.CreateModel(
            name='RideRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man_management.customer')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.frequency')),
            ],
        ),
        migrations.AddField(
            model_name='frequency',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_line', to='traffic_control.line'),
        ),
    ]
